notifications:
  email: false
language: clojure
jdk:
  - oraclejdk8
before_script:
  - npm install -g npm@latest
  - npm install phantomjs-prebuilt@latest
script:
  - lein test
  - lein cljsbuild once
  - ./node_modules/phantomjs-prebuilt/bin/phantomjs browser_test.js
